// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetCatalogue.Models;

namespace PlanetCatalogue.Migrations
{
    [DbContext(typeof(PlanetContext))]
    [Migration("20190322145914_AddSeed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlanetCatalogue.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Forests, mountains; home planet of the House of Organa.",
                            Image = "alderaan.png",
                            Name = "Alderaan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A gas planet with a thin layer of habitable atmosphere.",
                            Image = "bespin.jpg",
                            Name = "Bespin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cosmopolitan urban world consisting of one planet-wide city.",
                            Image = "coruscant.png",
                            Name = "Coruscant"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Desolate ice planet",
                            Image = "hoth.jpg",
                            Name = "Hoth"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Forest planet and home of the Wookiees",
                            Image = "kashyyyk.png",
                            Name = "Kashyyyk "
                        },
                        new
                        {
                            Id = 6,
                            Description = "Home of Boba Fett",
                            Image = "mandalore.png",
                            Name = "Mandalore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
