// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TroopCatalogue.Models;

namespace TroopCatalogue.Migrations
{
    [DbContext(typeof(TrooperContext))]
    [Migration("20190322151525_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TroopCatalogue.Models.Trooper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Troopers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "stromtrooper.png",
                            Name = "Stormtrooper"
                        },
                        new
                        {
                            Id = 2,
                            Image = "deathtrooper.png",
                            Name = "Death trooper"
                        },
                        new
                        {
                            Id = 3,
                            Image = "shadowtrooper.png",
                            Name = "Shadow trooper"
                        },
                        new
                        {
                            Id = 4,
                            Image = "scouttrooper.png",
                            Name = "Scout trooper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
